import Head from "next/head";

import Navbar from "../components/Navbar";
import DotGroup from "../components/DotGroup";
import Landing from "../components/Landing";
import LineGradient from "../components/LineGradient";
import Skills from "../components/Skills";
import ImageSlider from '../components/Certification'
import useMediaQuery from "../hooks/useMediaQuery";
import CustomToggleIcon from "@/components/CustomToggleIcon";



import { useState, useEffect } from "react";

export default function Home() {
  const [selectedPage, setSelectedPage] = useState("home");
  const [isTopOfPage, setisTopOfPage] = useState(true);
  const [gridSwitch, setGridSwitch] = useState(false);
  const isAboveMediumScreens = useMediaQuery("(min-width:1060px)");

  
  useEffect(() => {
    const handleScroll = () => {
      if (window.scrollY === 0) setisTopOfPage(true);
      if (window.scrollY !== 0) setisTopOfPage(false);
    };
    window.addEventListener("scroll", handleScroll);
    return () => window.removeEventListener("scroll", handleScroll);
  }, []);

  return (
    <>
      <Head>
        <title>Bilal Sidique</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="" />
      </Head>
      <main className={`app bg-deep-blue `}>
        <Navbar selectedPage={selectedPage} setSelectedPage={setSelectedPage} />
        <div className="xs:w-5/6 xs:mx-auto md:h-full ">
          {isAboveMediumScreens && (
            <DotGroup
              selectedPage={selectedPage}
              setSelectedPage={setSelectedPage}
            />
          )}
          <Landing setSelectedPage={setSelectedPage} />
        </div>
        <LineGradient />
        <div className=" ss:w-5/6 pb-20 mx-5 ss:mx-auto h-full mt-44 xs:mt-52">
          <div className="b-gradient-rainbow-bg"></div>
          <Skills />
        </div>

        <LineGradient ID="certifications" section="Certifications" />
        <div className="ss:w-5/6 pb-20 mx-5 ss:mx-auto h-full mt-32 xs:mt-36 ">
          {/* GRID VIEW SWITCH */}
          <div className=" flex items-center gap-3 justify-center xs:justify-start w-full mb-20">
            <p className="text-[22px] font-playfair">Grid View</p>
              <CustomToggleIcon gridSwitch={gridSwitch} setGridSwitch={setGridSwitch}  />
          </div>

          <div className={`md:w-full xs:w-full  glass  ${(isAboveMediumScreens && gridSwitch===false) && 'h-[600px]' }  mx-auto`}>
            <ImageSlider gridSwitch={gridSwitch} />
          </div>
        </div>


      </main>
    </>
  );
}
